name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: {}

jobs:
  build:
    name: Build (skip tests)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ '8', '11' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Temurin JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'

      - name: Show Java & Maven
        run: |
          java -version
          mvn -v

      - name: Build (skip tests)
        run: mvn -B -U -e clean package -DskipTests

      # 可选：上传构建产物，便于在 CI 面板下载
      - name: Upload JAR artifacts
        uses: actions/upload-artifact@v4
        with:
          name: marshalsec-jdk${{ matrix.java }}
          path: |
            **/target/*.jar
          if-no-files-found: warn
